services:
  skeleton:
    image: ghcr.io/medeiroz/skeleton:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.skeleton.rule=Host(`local.ticketeriaonline.com`)"
        - "traefik.http.routers.skeleton.entrypoints=web,websecure"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 8080:80
    networks:
      - web

networks:
  web:
    external: true
